Update deployment.yaml
fix the error about ssh

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -26,20 +26,15 @@ jobs:
           script: |
             mkdir -p ~/.ssh
 
-            # Use the existing SSH key named 'github'
-            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github
-            chmod 600 ~/.ssh/github
-
-            # Configure SSH to use the correct key for GitHub
-            echo "Host github.com
-            IdentityFile ~/.ssh/github
-            StrictHostKeyChecking no" > ~/.ssh/config
-
-            # Add GitHub's host key to known_hosts to prevent confirmation prompt
+            # Add GitHub private key for authentication
+            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+            chmod 600 ~/.ssh/id_rsa
+        
+            # Add GitHub to known hosts to prevent manual confirmation
             ssh-keyscan github.com >> ~/.ssh/known_hosts
-
+        
             # Test SSH connection with GitHub
-            ssh -i ~/.ssh/github -T git@github.com || exit 1
+            ssh -T git@github.com || exit 1
             set -e  # Exit on any error
 
             # Path to the .env file in the project directory
@@ -65,4 +60,16 @@ jobs:
             echo "NEXT_PUBLIC_REDIRECT_URI=${{ vars.NEXT_PUBLIC_REDIRECT_URI }}" >> $ENV_FILE
 
             # Continue the further Deployment process  
-            expor
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+            nvm install 20
+            cd /www/finanzoweb
+            eval $(ssh-agent); ssh-add ~/.ssh/id_rsa
+            git stash || echo "No changes to stash"
+            git pull origin main || exit 1
+            npm install || exit 1
+            npm i -g pm2
+            npm run build || exit 1  # Ensure build failure exits with error
+            pm2 install pm2-logrotate
+            pm2 restart dev_website || pm2 start npm --name "dev_website" -- start
+            pm2 save
